logging:
  log_file_name: youtube-scrape

mp3_loc: E:/Music/downloads/spring_2019_4
mp4_loc: E:/Music/downloads/mp4

youtube_list: C:\Users\aaron\PycharmProjects\youtube_scrape\song_lists\spring_2019_4.txt

mp4_mp3_toggle: mp3